\set ON_ERROR_STOP on

BEGIN;

CREATE OR REPLACE FUNCTION pg_temp.assert_true(condition BOOLEAN, message TEXT)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
  IF condition IS DISTINCT FROM TRUE THEN
    RAISE EXCEPTION 'CANONICAL_RECEPTION_TISS_ASSERTION_FAILED: %', message;
  END IF;
END;
$$;

SELECT pg_temp.assert_true(
  NOT has_function_privilege(
    'authenticated',
    'public.ensure_tiss_guide_for_checkin_secure(uuid,text,text)',
    'EXECUTE'
  )
  AND NOT has_function_privilege(
    'app_prontomedic',
    'public.ensure_tiss_guide_for_checkin_secure(uuid,text,text)',
    'EXECUTE'
  ),
  'Reception application roles must not create TISS guides'
);

SELECT pg_temp.assert_true(
  position(
    'requires_tiss'', false' IN lower(
      pg_get_functiondef(
        'public.start_reception_checkin_workflow_secure(bigint,text,jsonb)'::REGPROCEDURE
      )
    )
  ) > 0,
  'Reception workflow entrypoint must force requires_tiss=false'
);

SELECT pg_temp.assert_true(
  position(
    'guide_number_missing' IN pg_get_functiondef(
      'public.m39_billing_readiness(public.billing_accounts)'::REGPROCEDURE
    )
  ) = 0,
  'A guide generated by TISS cannot be a prerequisite for TISS readiness'
);

SELECT pg_temp.assert_true(
  EXISTS (
    SELECT 1
    FROM pg_trigger
    WHERE tgrelid = 'public.billing_accounts'::REGCLASS
      AND tgname = 'trg_m11_assign_billing_authorization'
      AND NOT tgisinternal
  )
  AND EXISTS (
    SELECT 1
    FROM pg_trigger
    WHERE tgrelid = 'public.billing_accounts'::REGCLASS
      AND tgname = 'trg_m39_advance_reviewed_billing_account'
      AND NOT tgisinternal
  ),
  'Billing authorization and review transition invariants must be active'
);

SELECT pg_temp.assert_true(
  position(
    'item.status IN (''agendado'', ''liberado_worklist'')' IN
    pg_get_functiondef(
      'public.release_appointment_to_worklist_secure(bigint,text)'::REGPROCEDURE
    )
  ) > 0,
  'Worklist release must resume after an item was already marked as released'
);

SELECT pg_temp.assert_true(
  position(
    'dicom_worklist_queue.idempotency_key = EXCLUDED.idempotency_key' IN
    pg_get_functiondef(
      'public.release_appointment_to_worklist_secure(bigint,text)'::REGPROCEDURE
    )
  ) > 0,
  'Worklist resume must reject a conflicting idempotency key'
);

SELECT pg_temp.assert_true(
  NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'dicom_worklist_queue'
      AND column_name IN (
        'unit_id', 'appointment_id', 'imaging_order_item_id',
        'idempotency_key', 'patient_id', 'patient_identifier',
        'requested_procedure_id', 'scheduled_procedure_step_id',
        'scheduled_station_aetitle', 'scheduled_datetime'
      )
      AND is_nullable = 'YES'
  ),
  'Canonical DICOM worklist identity and projection fields must be required'
);

SELECT pg_temp.assert_true(
  EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'public.dicom_worklist_queue'::REGCLASS
      AND conname = 'dicom_worklist_queue_imaging_order_item_id_fkey'
  )
  AND EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'public.dicom_worklist_queue'::REGCLASS
      AND conname = 'dicom_worklist_queue_patient_id_fkey'
  )
  AND EXISTS (
    SELECT 1
    FROM pg_class index_relation
    JOIN pg_namespace index_namespace
      ON index_namespace.oid = index_relation.relnamespace
    WHERE index_namespace.nspname = 'public'
      AND index_relation.relname = 'dicom_worklist_queue_company_item_uq'
      AND index_relation.relkind = 'i'
  ),
  'DICOM worklist queue must enforce item, patient and uniqueness integrity'
);

ROLLBACK;
