#!/usr/bin/env bash
set -Eeuo pipefail

helper="${BASH_SOURCE[0]%/*}/deploy-migration.sh"
integration="${BASH_SOURCE[0]%/*}/deploy-migration.integration.sh"
workflow="${BASH_SOURCE[0]%/*}/../../.github/workflows/deploy-database-migration.yml"
ci_workflow="${BASH_SOURCE[0]%/*}/../../.github/workflows/ci.yml"
auth_workflow="${BASH_SOURCE[0]%/*}/../../.github/workflows/deploy-edge-functions.yml"
rollback="${BASH_SOURCE[0]%/*}/../../supabase/rollbacks/20260804143000_rbac_active_context_aal2.sql"
auth_admin_rollback="${BASH_SOURCE[0]%/*}/../../supabase/rollbacks/20260805123000_auth_admin_suspension_invariants.sql"
worklist_rollback="${BASH_SOURCE[0]%/*}/../../supabase/rollbacks/20260811120000_reception_worklist_handoff.sql"
dicom_rollback="${BASH_SOURCE[0]%/*}/../../supabase/rollbacks/20260811210000_dicom_worklist_rls_hardening.sql"
pharmacy_rollback="${BASH_SOURCE[0]%/*}/../../supabase/rollbacks/20260812021457_pharmacy_runtime_closure.sql"
medical_attendance_rollback="${BASH_SOURCE[0]%/*}/../../supabase/rollbacks/20260812150000_medical_attendance_atomic_completion.sql"
clinical_billing_rollback="${BASH_SOURCE[0]%/*}/../../supabase/rollbacks/20260812170000_medical_attendance_billing_handoff.sql"
runtime_rpc_rollback="${BASH_SOURCE[0]%/*}/../../supabase/rollbacks/20260829012947_canonical_runtime_rpc_contracts.sql"
catalog_rollback="${BASH_SOURCE[0]%/*}/../../supabase/rollbacks/20260829013235_close_global_catalog_write_policies.sql"
auth_session_rollback="${BASH_SOURCE[0]%/*}/../../supabase/rollbacks/20260829014500_auth_native_session_contract.sql"
nursing_owner_rollback="${BASH_SOURCE[0]%/*}/../../supabase/rollbacks/20260902022540_nursing_rpc_owner_rls_closure.sql"
appointment_series_rollback="${BASH_SOURCE[0]%/*}/../../supabase/rollbacks/20260902055133_appointment_series_requirements_contract.sql"
appointment_series_migration="${BASH_SOURCE[0]%/*}/../../supabase/migrations/20260902055133_appointment_series_requirements_contract.sql"
tiss_authorization_rollback="${BASH_SOURCE[0]%/*}/../../supabase/rollbacks/20260904183653_tiss_authorization_serialization.sql"
tiss_authorization_migration="${BASH_SOURCE[0]%/*}/../../supabase/migrations/20260904183653_tiss_authorization_serialization.sql"
imaging_order_attendance_rollback="${BASH_SOURCE[0]%/*}/../../supabase/rollbacks/20260905030000_imaging_order_attendance_contract.sql"
pre_cadastro_edge_migration="${BASH_SOURCE[0]%/*}/../../supabase/migrations/20260910223000_secure_pre_cadastro_edge_contract.sql"
pre_cadastro_edge_rollback="${BASH_SOURCE[0]%/*}/../../supabase/rollbacks/20260910223000_secure_pre_cadastro_edge_contract.sql"
pre_cadastro_contract_migration="${BASH_SOURCE[0]%/*}/../../supabase/migrations/20260910224500_retire_legacy_pre_cadastro_rpc_grants.sql"
pre_cadastro_contract_rollback="${BASH_SOURCE[0]%/*}/../../supabase/rollbacks/20260910224500_retire_legacy_pre_cadastro_rpc_grants.sql"
pre_cadastro_cleanup_migration="${BASH_SOURCE[0]%/*}/../../supabase/migrations/20260910230000_purge_legacy_pre_cadastro_plaintext.sql"
pre_cadastro_cleanup_rollback="${BASH_SOURCE[0]%/*}/../../supabase/rollbacks/20260910230000_purge_legacy_pre_cadastro_plaintext.sql"

bash -n "$helper"
test -f "$integration"
test -f "$workflow"
test -f "$ci_workflow"
test -f "$auth_workflow"
test -f "$rollback"
test -f "$auth_admin_rollback"
test -f "$worklist_rollback"
test -f "$dicom_rollback"
test -f "$pharmacy_rollback"
test -f "$medical_attendance_rollback"
test -f "$clinical_billing_rollback"
test -f "$runtime_rpc_rollback"
test -f "$catalog_rollback"
test -f "$auth_session_rollback"
test -f "$nursing_owner_rollback"
test -f "$appointment_series_rollback"
test -f "$appointment_series_migration"
test -f "$tiss_authorization_rollback"
test -f "$tiss_authorization_migration"
test -f "$imaging_order_attendance_rollback"
test -f "$pre_cadastro_edge_migration"
test -f "$pre_cadastro_edge_rollback"
test -f "$pre_cadastro_contract_migration"
test -f "$pre_cadastro_contract_rollback"
test -f "$pre_cadastro_cleanup_migration"
test -f "$pre_cadastro_cleanup_rollback"
test -f "${BASH_SOURCE[0]%/*}/../../tests/database/pre_cadastro_expand_compatibility.sql"
grep -Fq 'PRONTOMEDIC_GLOBAL_DEPLOY_LOCK' "$helper"
grep -Fq 'exec 9>"$global_lock"' "$helper"
test "$(grep -Fc 'group: prontomedic-production-deploy' "$workflow")" = 1
test "$(grep -Fc 'group: prontomedic-production-deploy' "$auth_workflow")" = 1
grep -Fq 'image: postgres:16' "$ci_workflow"
grep -Fq 'pg_dump -Fc' "$helper"
grep -Fq 'pg_restore --exit-on-error' "$helper"
grep -Fq 'pg_restore --exit-on-error -d "$restore_db" <"$backup"' "$helper"
grep -Fq 'supabase_migrations.schema_migrations' "$helper"
grep -Fq 'rollback_on_error' "$helper"
grep -Fq "tup_inserted || ':' || tup_updated || ':' || tup_deleted" "$helper"
! grep -Fq 'txid_snapshot_xmax(txid_current_snapshot())' "$helper"
! grep -Fq 'pg_current_wal_lsn' "$helper"
grep -Fq 'history_absent' "$helper"
grep -Fq 'history_present' "$helper"
grep -Fq 'require_predecessor' "$helper"
grep -Fq 'rollback_mode' "$helper"
grep -Fq 'STATE_RECORD' "$helper"
grep -Fq 'promote_previous_state' "$helper"
grep -Fq 'snapshot_coordinator_state "$backup"' "$helper"
grep -Fq 'validate_state_snapshot "$backup" "$rehearsal_db" "$desired_state"' "$helper"
grep -Fq 'apply_state_snapshot "$desired_state"' "$helper"
grep -Fq 'PRONTOMEDIC_DB_INJECT_RESTORE_STATE_FAILURE' "$helper"
grep -Fq 'migration fora da allowlist do coordenador' "$helper"
grep -Fq '20260804033225:secure_companies_units_admin_contract' "$helper"
grep -Fq '20260804143000:rbac_active_context_aal2' "$helper"
grep -Fq '20260805123000:auth_admin_suspension_invariants' "$helper"
grep -Fq '20260811120000:reception_worklist_handoff:20260805123000:inverse' "$helper"
grep -Fq '20260811210000:dicom_worklist_rls_hardening:20260811120000:forward_only' "$helper"
grep -Fq '20260812021457:pharmacy_runtime_closure:20260811210000:preserve_schema' "$helper"
grep -Fq '20260812150000:medical_attendance_atomic_completion:20260812021457:preserve_schema' "$helper"
grep -Fq '20260812170000:medical_attendance_billing_handoff:20260812150000:preserve_schema' "$helper"
grep -Fq '20260829012947:canonical_runtime_rpc_contracts:20260813001000:preserve_schema' "$helper"
grep -Fq '20260829013235:close_global_catalog_write_policies:20260829012947:forward_only' "$helper"
grep -Fq '20260829014500:auth_native_session_contract:20260829013235:forward_only' "$helper"
grep -Fq '20260902022540:nursing_rpc_owner_rls_closure:20260829014500:preserve_schema' "$helper"
grep -Fq '20260902055133:appointment_series_requirements_contract:20260902022540:preserve_schema' "$helper"
grep -Fq '20260904183653:tiss_authorization_serialization:20260902055133:preserve_schema' "$helper"
grep -Fq '20260905030000:imaging_order_attendance_contract:20260904183653:inverse' "$helper"
grep -Fq '20260910223000:secure_pre_cadastro_edge_contract:20260905030000:preserve_schema' "$helper"
grep -Fq '20260910224500:retire_legacy_pre_cadastro_rpc_grants:20260910223000:inverse' "$helper"
grep -Fq '20260910230000:purge_legacy_pre_cadastro_plaintext:20260910224500:preserve_schema' "$helper"
grep -Fq '20260910223000|secure_pre_cadastro_edge_contract|20260905030000|preserve_schema|pre-cadastro-edge' "$integration"
grep -Fq '20260910224500|retire_legacy_pre_cadastro_rpc_grants|20260910223000|inverse|pre-cadastro-contract' "$integration"
grep -Fq '20260910230000|purge_legacy_pre_cadastro_plaintext|20260910224500|preserve_schema|pre-cadastro-cleanup' "$integration"
grep -Fq 'pre_cadastro_expand_compatibility.sql' "$integration"
grep -Fq 'test_pre_cadastro_contract_concurrency' "$integration"
grep -Fq 'pre_cadastro_legacy_writer' "$integration"
grep -Fq 'pre_cadastro_cleanup' "$integration"
grep -Fq 'test "$MIGRATION_VERSION" = 20260910224500' "$integration"
grep -Fq 'restore com falha injetada terminou com sucesso' "$integration"
grep -Fq "version = '20260910224500'\" -d \"\$database\")\" = 0" "$integration"
grep -Fq 'test "$MIGRATION_VERSION" = 20260910223000' "$integration"
grep -Fq "p.proname IN ('create_pre_cadastro', 'confirm_pre_cadastro')" "$pre_cadastro_contract_migration"
grep -Fq 'FROM PUBLIC, anon, authenticated' "$pre_cadastro_contract_migration"
grep -Fq 'cat "supabase/migrations/${version}_${name}.sql"' "$integration"
grep -Fq "WHERE version = '20260905030000'" "$imaging_order_attendance_rollback"
grep -Fq 'migration_version:' "$workflow"
grep -Fq '20260804143000) name=rbac_active_context_aal2' "$workflow"
grep -Fq '20260805123000) name=auth_admin_suspension_invariants' "$workflow"
grep -Fq '20260811120000) name=reception_worklist_handoff' "$workflow"
grep -Fq '20260811210000) name=dicom_worklist_rls_hardening' "$workflow"
grep -Fq '20260812021457) name=pharmacy_runtime_closure' "$workflow"
grep -Fq '20260812150000) name=medical_attendance_atomic_completion' "$workflow"
grep -Fq '20260812170000) name=medical_attendance_billing_handoff' "$workflow"
grep -Fq '20260829012947) name=canonical_runtime_rpc_contracts' "$workflow"
grep -Fq '20260829013235) name=close_global_catalog_write_policies' "$workflow"
grep -Fq '20260829014500) name=auth_native_session_contract' "$workflow"
grep -Fq '20260902022540) name=nursing_rpc_owner_rls_closure' "$workflow"
grep -Fq '20260902055133) name=appointment_series_requirements_contract' "$workflow"
grep -Fq '20260904183653) name=tiss_authorization_serialization' "$workflow"
grep -Fq '20260905030000) name=imaging_order_attendance_contract' "$workflow"
grep -Fq '20260910223000) name=secure_pre_cadastro_edge_contract; predecessor=20260905030000; rollback_mode=preserve_schema' "$workflow"
grep -Fq '20260910224500) name=retire_legacy_pre_cadastro_rpc_grants; predecessor=20260910223000; rollback_mode=inverse' "$workflow"
grep -Fq '20260910230000) name=purge_legacy_pre_cadastro_plaintext; predecessor=20260910224500; rollback_mode=preserve_schema' "$workflow"
grep -Fq '20260910223000) smoke_prefix=deploy/database/pre-cadastro-edge' "$workflow"
grep -Fq '20260910224500) smoke_prefix=deploy/database/pre-cadastro-contract' "$workflow"
grep -Fq '20260910230000) smoke_prefix=deploy/database/pre-cadastro-cleanup' "$workflow"
grep -Fq 'cat "supabase/migrations/${version}_${name}.sql"' "$workflow"
grep -Fq 'predecessorVersion' "$workflow"
grep -Fq 'rollbackMode' "$workflow"
grep -Fq 'ensure_history "$restore_db"' "$helper"
grep -Fq 'ensure_history "$database"' "$helper"
grep -Fq 'find "$destination" -type f -exec chmod 0644' "$helper"
grep -Fq 'policy de escrita desconhecida em units' "${BASH_SOURCE[0]%/*}/smoke-before.sql"
grep -Fq 'policy desconhecida em role_permissions' "${BASH_SOURCE[0]%/*}/rbac-before.sql"
grep -Fq 'authenticated possui escrita direta em role_permissions' "${BASH_SOURCE[0]%/*}/rbac-before.sql"
! grep -Fq 'merge-base --is-ancestor' "$workflow"
grep -Fq 'test "$(git rev-parse origin/main)" = "$COMMIT_SHA"' "$workflow"
grep -Fq 'actions: read' "$workflow"
grep -Fq '/actions/workflows/ci.yml/runs?head_sha=' "$workflow"
grep -Fq "latest.status !== 'completed' || latest.conclusion !== 'success'" "$workflow"
grep -Fq 'environment: Production' "$workflow"
grep -Fq '/etc/sudoers.d/prontomedic-db-deploy' "$workflow"
grep -Fq '/usr/sbin/visudo -cf' "$workflow"
grep -Eq '^[[:space:]]*BEGIN;' "$rollback"
grep -Eq '^[[:space:]]*COMMIT;' "$rollback"
! grep -Fq 'USING (TRUE)' "$rollback"
grep -Fq 'USING (company_id = public.active_company_id())' "$rollback"
grep -Eq '^[[:space:]]*BEGIN;' "$auth_admin_rollback"
grep -Eq '^[[:space:]]*COMMIT;' "$auth_admin_rollback"
grep -Fq 'prepare_user_access_active(UUID, UUID, BOOLEAN)' "$auth_admin_rollback"
grep -Fq "version = '20260804143000'" "$rollback"
grep -Fq "version = '20260805123000'" "$auth_admin_rollback"
grep -Fq "version = '20260811120000'" "$worklist_rollback"
! grep -Fq 'DELETE FROM supabase_migrations.schema_migrations' "$dicom_rollback"
! grep -Fq 'DELETE FROM supabase_migrations.schema_migrations' "$pharmacy_rollback"
! grep -Fq 'DELETE FROM supabase_migrations.schema_migrations' "$medical_attendance_rollback"
! grep -Fq 'DELETE FROM supabase_migrations.schema_migrations' "$clinical_billing_rollback"
grep -Fq 'm18_finalize_appointment_with_billing_secure' "$clinical_billing_rollback"
grep -Fq 'm18_complete_attendance_secure' "$medical_attendance_rollback"
grep -Fq 'REVOKE EXECUTE ON FUNCTION public.dispensar_estoque_atomic' "$pharmacy_rollback"
for prefix in worklist-handoff dicom-hardening pharmacy medical-attendance clinical-billing; do
  for phase in before applied rollback; do
    test -f "${BASH_SOURCE[0]%/*}/${prefix}-${phase}.sql"
  done
done
for prefix in canonical-runtime-rpc global-catalog-write auth-native-session nursing-rpc-owner appointment-series tiss-authorization; do
  for phase in before applied rollback; do
    test -f "${BASH_SOURCE[0]%/*}/${prefix}-${phase}.sql"
  done
done
for phase in before applied rollback; do
  test -f "${BASH_SOURCE[0]%/*}/pre-cadastro-edge-${phase}.sql"
done
grep -Eq '^[[:space:]]*BEGIN;' "$appointment_series_rollback"
grep -Eq '^[[:space:]]*COMMIT;' "$appointment_series_rollback"
grep -Fq 'create_appointment_series_with_requirements_secure' "$appointment_series_rollback"
grep -Eq '^[[:space:]]*BEGIN;' "$appointment_series_migration"
grep -Eq '^[[:space:]]*COMMIT;' "$appointment_series_migration"
grep -Fq 'AND lg_ativo = TRUE' "$appointment_series_migration"
! grep -Fq 'AND is_active = TRUE' "$appointment_series_migration"
grep -Eq '^[[:space:]]*BEGIN;' "$tiss_authorization_migration"
grep -Eq '^[[:space:]]*COMMIT;' "$tiss_authorization_migration"
grep -Fq '<ans:dadosAutorizacao>' "$tiss_authorization_migration"
grep -Fq '<ans:numeroGuiaOperadora>' "$tiss_authorization_migration"
grep -Fq '<ans:dataAutorizacao>' "$tiss_authorization_migration"
grep -Eq '^[[:space:]]*BEGIN;' "$tiss_authorization_rollback"
grep -Eq '^[[:space:]]*COMMIT;' "$tiss_authorization_rollback"
grep -Eq '^[[:space:]]*BEGIN;' "$nursing_owner_rollback"
grep -Eq '^[[:space:]]*COMMIT;' "$nursing_owner_rollback"
grep -Fq 'nursing_administer_medication_secure' "$nursing_owner_rollback"
grep -Fq 'nursing_refuse_medication_secure' "$nursing_owner_rollback"
for rollback_file in "$runtime_rpc_rollback" "$catalog_rollback" "$auth_session_rollback"; do
  grep -Eq '^[[:space:]]*BEGIN;' "$rollback_file"
  grep -Eq '^[[:space:]]*COMMIT;' "$rollback_file"
  ! grep -Fq 'DELETE FROM supabase_migrations.schema_migrations' "$rollback_file"
done
grep -Eq '^[[:space:]]*BEGIN;' "$pre_cadastro_edge_rollback"
grep -Eq '^[[:space:]]*COMMIT;' "$pre_cadastro_edge_rollback"
! grep -Fq 'DELETE FROM supabase_migrations.schema_migrations' "$pre_cadastro_edge_rollback"
grep -Fq 'PRESERVE_SCHEMA' "$pre_cadastro_edge_rollback"
grep -Fq 'application rollback remains compatible' "$pre_cadastro_edge_rollback"
grep -Fq "version = '20260910223000'" "${BASH_SOURCE[0]%/*}/pre-cadastro-edge-applied.sql"
grep -Fq '\ir smoke-applied.sql' "${BASH_SOURCE[0]%/*}/pre-cadastro-edge-rollback.sql"
grep -Eq '^[[:space:]]*BEGIN;' "$pre_cadastro_contract_migration"
grep -Eq '^[[:space:]]*COMMIT;' "$pre_cadastro_contract_migration"
grep -Fq 'LOCK TABLE public.pre_cadastro IN SHARE ROW EXCLUSIVE MODE' "$pre_cadastro_cleanup_migration"
grep -Fq "pg_advisory_xact_lock_shared" "$pre_cadastro_edge_migration"
grep -Fq "pg_advisory_xact_lock" "$pre_cadastro_cleanup_migration"
grep -Fq 'token plaintext sem hash equivalente impede retirada segura' "$pre_cadastro_cleanup_migration"
grep -Fq 'overload legado desconhecido impede retirada segura' "$pre_cadastro_contract_migration"
grep -Eq '^[[:space:]]*BEGIN;' "$pre_cadastro_contract_rollback"
grep -Eq '^[[:space:]]*COMMIT;' "$pre_cadastro_contract_rollback"
! grep -Fq 'FOR legacy_function IN' "$pre_cadastro_contract_rollback"
grep -Fq "WHERE version = '20260910224500'" "$pre_cadastro_contract_rollback"
for phase in before applied rollback; do
  test -f "${BASH_SOURCE[0]%/*}/pre-cadastro-contract-${phase}.sql"
  test -f "${BASH_SOURCE[0]%/*}/pre-cadastro-cleanup-${phase}.sql"
done
grep -Fq 'PRESERVE_SCHEMA' "$pre_cadastro_cleanup_rollback"
! grep -Fq 'prontomedic-auth-deploy' "$workflow"
grep -Fq '/usr/local/sbin/prontomedic-edge-deploy --audit-contract' "$workflow"

echo 'DATABASE_DEPLOY_STATIC_CONTRACT_PASS'
