#!/usr/bin/env bash
set -Eeuo pipefail

helper="${BASH_SOURCE[0]%/*}/deploy-migration.sh"
workflow="${BASH_SOURCE[0]%/*}/../../.github/workflows/deploy-database-migration.yml"
ci_workflow="${BASH_SOURCE[0]%/*}/../../.github/workflows/ci.yml"
auth_workflow="${BASH_SOURCE[0]%/*}/../../.github/workflows/deploy-edge-functions.yml"
rollback="${BASH_SOURCE[0]%/*}/../../supabase/rollbacks/20260804143000_rbac_active_context_aal2.sql"
auth_admin_rollback="${BASH_SOURCE[0]%/*}/../../supabase/rollbacks/20260805123000_auth_admin_suspension_invariants.sql"
worklist_rollback="${BASH_SOURCE[0]%/*}/../../supabase/rollbacks/20260811120000_reception_worklist_handoff.sql"
dicom_rollback="${BASH_SOURCE[0]%/*}/../../supabase/rollbacks/20260811210000_dicom_worklist_rls_hardening.sql"
pharmacy_rollback="${BASH_SOURCE[0]%/*}/../../supabase/rollbacks/20260812021457_pharmacy_runtime_closure.sql"
medical_attendance_rollback="${BASH_SOURCE[0]%/*}/../../supabase/rollbacks/20260812150000_medical_attendance_atomic_completion.sql"
clinical_billing_rollback="${BASH_SOURCE[0]%/*}/../../supabase/rollbacks/20260812170000_medical_attendance_billing_handoff.sql"

bash -n "$helper"
test -f "$workflow"
test -f "$ci_workflow"
test -f "$auth_workflow"
test -f "$rollback"
test -f "$auth_admin_rollback"
test -f "$worklist_rollback"
test -f "$dicom_rollback"
test -f "$pharmacy_rollback"
test -f "$medical_attendance_rollback"
test -f "$clinical_billing_rollback"
grep -Fq 'PRONTOMEDIC_GLOBAL_DEPLOY_LOCK' "$helper"
grep -Fq 'exec 9>"$global_lock"' "$helper"
test "$(grep -Fc 'group: prontomedic-production-deploy' "$workflow")" = 1
test "$(grep -Fc 'group: prontomedic-production-deploy' "$auth_workflow")" = 1
grep -Fq 'image: postgres:16' "$ci_workflow"
grep -Fq 'pg_dump -Fc' "$helper"
grep -Fq 'pg_restore --exit-on-error' "$helper"
grep -Fq 'pg_restore --exit-on-error -d "$restore_db" <"$backup"' "$helper"
grep -Fq 'supabase_migrations.schema_migrations' "$helper"
grep -Fq 'rollback_on_error' "$helper"
grep -Fq 'history_absent' "$helper"
grep -Fq 'history_present' "$helper"
grep -Fq 'require_predecessor' "$helper"
grep -Fq 'rollback_mode' "$helper"
grep -Fq 'STATE_RECORD' "$helper"
grep -Fq 'promote_previous_state' "$helper"
grep -Fq 'migration fora da allowlist do coordenador' "$helper"
grep -Fq '20260804033225:secure_companies_units_admin_contract' "$helper"
grep -Fq '20260804143000:rbac_active_context_aal2' "$helper"
grep -Fq '20260805123000:auth_admin_suspension_invariants' "$helper"
grep -Fq '20260811120000:reception_worklist_handoff:20260805123000:inverse' "$helper"
grep -Fq '20260811210000:dicom_worklist_rls_hardening:20260811120000:forward_only' "$helper"
grep -Fq '20260812021457:pharmacy_runtime_closure:20260811210000:preserve_schema' "$helper"
grep -Fq '20260812150000:medical_attendance_atomic_completion:20260812021457:preserve_schema' "$helper"
grep -Fq '20260812170000:medical_attendance_billing_handoff:20260812150000:preserve_schema' "$helper"
grep -Fq 'migration_version:' "$workflow"
grep -Fq '20260804143000) name=rbac_active_context_aal2' "$workflow"
grep -Fq '20260805123000) name=auth_admin_suspension_invariants' "$workflow"
grep -Fq '20260811120000) name=reception_worklist_handoff' "$workflow"
grep -Fq '20260811210000) name=dicom_worklist_rls_hardening' "$workflow"
grep -Fq '20260812021457) name=pharmacy_runtime_closure' "$workflow"
grep -Fq '20260812150000) name=medical_attendance_atomic_completion' "$workflow"
grep -Fq '20260812170000) name=medical_attendance_billing_handoff' "$workflow"
grep -Fq 'predecessorVersion' "$workflow"
grep -Fq 'rollbackMode' "$workflow"
grep -Fq 'ensure_history "$restore_db"' "$helper"
grep -Fq 'ensure_history "$database"' "$helper"
grep -Fq 'find "$destination" -type f -exec chmod 0644' "$helper"
grep -Fq 'policy de escrita desconhecida em units' "${BASH_SOURCE[0]%/*}/smoke-before.sql"
grep -Fq 'policy desconhecida em role_permissions' "${BASH_SOURCE[0]%/*}/rbac-before.sql"
grep -Fq 'authenticated possui escrita direta em role_permissions' "${BASH_SOURCE[0]%/*}/rbac-before.sql"
grep -Fq 'merge-base --is-ancestor' "$workflow"
grep -Fq 'environment: Production' "$workflow"
grep -Fq '/etc/sudoers.d/prontomedic-db-deploy' "$workflow"
grep -Fq '/usr/sbin/visudo -cf' "$workflow"
grep -Eq '^[[:space:]]*BEGIN;' "$rollback"
grep -Eq '^[[:space:]]*COMMIT;' "$rollback"
! grep -Fq 'USING (TRUE)' "$rollback"
grep -Fq 'USING (company_id = public.active_company_id())' "$rollback"
grep -Eq '^[[:space:]]*BEGIN;' "$auth_admin_rollback"
grep -Eq '^[[:space:]]*COMMIT;' "$auth_admin_rollback"
grep -Fq 'prepare_user_access_active(UUID, UUID, BOOLEAN)' "$auth_admin_rollback"
grep -Fq "version = '20260804143000'" "$rollback"
grep -Fq "version = '20260805123000'" "$auth_admin_rollback"
grep -Fq "version = '20260811120000'" "$worklist_rollback"
! grep -Fq 'DELETE FROM supabase_migrations.schema_migrations' "$dicom_rollback"
! grep -Fq 'DELETE FROM supabase_migrations.schema_migrations' "$pharmacy_rollback"
! grep -Fq 'DELETE FROM supabase_migrations.schema_migrations' "$medical_attendance_rollback"
! grep -Fq 'DELETE FROM supabase_migrations.schema_migrations' "$clinical_billing_rollback"
grep -Fq 'm18_finalize_appointment_with_billing_secure' "$clinical_billing_rollback"
grep -Fq 'm18_complete_attendance_secure' "$medical_attendance_rollback"
grep -Fq 'REVOKE EXECUTE ON FUNCTION public.dispensar_estoque_atomic' "$pharmacy_rollback"
for prefix in worklist-handoff dicom-hardening pharmacy medical-attendance clinical-billing; do
  for phase in before applied rollback; do
    test -f "${BASH_SOURCE[0]%/*}/${prefix}-${phase}.sql"
  done
done
! grep -Fq 'prontomedic-auth-deploy' "$workflow"
! grep -Fq 'prontomedic-edge-deploy' "$workflow"

echo 'DATABASE_DEPLOY_STATIC_CONTRACT_PASS'
