-- Módulo 1: fundação canônica de identidade, RBAC, RLS e auditoria.
-- Esta migration é incremental: não reescreve o histórico já aplicado em produção.

-- ---------------------------------------------------------------------------
-- Papéis e matriz de permissões por empresa
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.roles (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  description TEXT,
  lg_ativo BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.roles ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE public.roles ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE public.roles ADD COLUMN IF NOT EXISTS lg_ativo BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE public.roles ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE public.roles ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

CREATE UNIQUE INDEX IF NOT EXISTS roles_name_unique_idx
  ON public.roles (name);

INSERT INTO public.roles (name, description)
VALUES
  ('admin', 'Administrador da empresa'),
  ('medico', 'Profissional médico'),
  ('recepcao', 'Equipe de recepção'),
  ('enfermagem', 'Equipe de enfermagem'),
  ('laboratorio', 'Equipe de laboratório'),
  ('financeiro', 'Equipe financeira'),
  ('farmacia', 'Equipe de farmácia'),
  ('dpo', 'Encarregado de proteção de dados')
ON CONFLICT (name) DO UPDATE
SET description = EXCLUDED.description,
    lg_ativo = TRUE,
    updated_at = NOW();

CREATE TABLE IF NOT EXISTS public.role_permissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  role_id INTEGER NOT NULL REFERENCES public.roles(id) ON DELETE CASCADE,
  module TEXT NOT NULL,
  can_view BOOLEAN NOT NULL DEFAULT FALSE,
  can_create BOOLEAN NOT NULL DEFAULT FALSE,
  can_edit BOOLEAN NOT NULL DEFAULT FALSE,
  can_delete BOOLEAN NOT NULL DEFAULT FALSE,
  can_export BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT role_permissions_company_role_module_key
    UNIQUE (company_id, role_id, module)
);

ALTER TABLE public.role_permissions ADD COLUMN IF NOT EXISTS company_id UUID;
ALTER TABLE public.role_permissions ADD COLUMN IF NOT EXISTS role_id INTEGER;
ALTER TABLE public.role_permissions ADD COLUMN IF NOT EXISTS module TEXT;
ALTER TABLE public.role_permissions ADD COLUMN IF NOT EXISTS can_view BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE public.role_permissions ADD COLUMN IF NOT EXISTS can_create BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE public.role_permissions ADD COLUMN IF NOT EXISTS can_edit BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE public.role_permissions ADD COLUMN IF NOT EXISTS can_delete BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE public.role_permissions ADD COLUMN IF NOT EXISTS can_export BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE public.role_permissions ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE public.role_permissions ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

-- Em instalações legadas, uma matriz sem empresa só pode ser migrada
-- automaticamente quando existe uma única empresa. Com múltiplas empresas,
-- abortamos em vez de atribuir permissões ao tenant errado.
DO $$
DECLARE
  v_company_count INTEGER;
  v_company_id UUID;
BEGIN
  IF EXISTS (SELECT 1 FROM public.role_permissions WHERE company_id IS NULL) THEN
    SELECT COUNT(*), MIN(id) INTO v_company_count, v_company_id
    FROM public.companies;

    IF v_company_count <> 1 THEN
      RAISE EXCEPTION
        'AUTH_FOUNDATION_PREFLIGHT: role_permissions sem company_id e % empresas; mapeamento manual obrigatório',
        v_company_count;
    END IF;

    UPDATE public.role_permissions
       SET company_id = v_company_id
     WHERE company_id IS NULL;
  END IF;
END;
$$;

ALTER TABLE public.role_permissions
  ALTER COLUMN company_id SET NOT NULL,
  ALTER COLUMN role_id SET NOT NULL,
  ALTER COLUMN module SET NOT NULL;

DO $$
DECLARE
  v_constraint RECORD;
BEGIN
  -- Remove apenas uniques legadas exatamente sobre (role_id,module).
  FOR v_constraint IN
    SELECT c.conname
    FROM pg_constraint c
    WHERE c.conrelid = 'public.role_permissions'::regclass
      AND c.contype = 'u'
      AND (
        SELECT array_agg(a.attname ORDER BY key.ordinality)
        FROM unnest(c.conkey) WITH ORDINALITY AS key(attnum, ordinality)
        JOIN pg_attribute a
          ON a.attrelid = c.conrelid
         AND a.attnum = key.attnum
      ) = ARRAY['role_id', 'module']::name[]
  LOOP
    EXECUTE format('ALTER TABLE public.role_permissions DROP CONSTRAINT %I', v_constraint.conname);
  END LOOP;
END;
$$;

CREATE UNIQUE INDEX IF NOT EXISTS role_permissions_company_role_module_idx
  ON public.role_permissions (company_id, role_id, module);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'public.role_permissions'::regclass
      AND contype = 'f'
      AND confrelid = 'public.companies'::regclass
  ) THEN
    ALTER TABLE public.role_permissions
      ADD CONSTRAINT role_permissions_company_id_fkey
      FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'public.role_permissions'::regclass
      AND contype = 'f'
      AND confrelid = 'public.roles'::regclass
  ) THEN
    ALTER TABLE public.role_permissions
      ADD CONSTRAINT role_permissions_role_id_fkey
      FOREIGN KEY (role_id) REFERENCES public.roles(id) ON DELETE CASCADE;
  END IF;
END;
$$;

-- ---------------------------------------------------------------------------
-- Identidade canônica: public.user_profiles.id = auth.users.id
-- ---------------------------------------------------------------------------
UPDATE public.user_profiles
   SET user_id = id
 WHERE user_id IS NULL;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM public.user_profiles
    WHERE user_id IS DISTINCT FROM id
  ) THEN
    RAISE EXCEPTION
      'AUTH_FOUNDATION_PREFLIGHT: user_profiles.id e user_id divergentes; reconciliação manual obrigatória';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.user_profiles up
    LEFT JOIN auth.users au ON au.id = up.id
    WHERE au.id IS NULL
  ) THEN
    RAISE EXCEPTION
      'AUTH_FOUNDATION_PREFLIGHT: existem user_profiles órfãos sem auth.users correspondente';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.user_profiles up
    LEFT JOIN public.roles r ON r.id = up.role_id
    WHERE up.role_id IS NOT NULL AND r.id IS NULL
  ) THEN
    RAISE EXCEPTION
      'AUTH_FOUNDATION_PREFLIGHT: existem role_id sem papel correspondente';
  END IF;
END;
$$;

UPDATE public.user_profiles up
   SET role_id = r.id,
       role_name = r.name
  FROM public.roles r
 WHERE up.role_id IS NULL
   AND CASE lower(COALESCE(up.role_name, ''))
         WHEN 'médico' THEN 'medico'
         WHEN 'recepção' THEN 'recepcao'
         WHEN 'enfermeiro' THEN 'enfermagem'
         ELSE lower(COALESCE(up.role_name, ''))
       END = r.name;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'public.user_profiles'::regclass
      AND contype = 'f'
      AND confrelid = 'auth.users'::regclass
      AND conkey = ARRAY[(SELECT attnum FROM pg_attribute
                          WHERE attrelid = 'public.user_profiles'::regclass
                            AND attname = 'id')]::smallint[]
  ) THEN
    ALTER TABLE public.user_profiles
      ADD CONSTRAINT user_profiles_id_auth_users_fkey
      FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'public.user_profiles'::regclass
      AND contype = 'f'
      AND confrelid = 'public.roles'::regclass
      AND conkey = ARRAY[(SELECT attnum FROM pg_attribute
                          WHERE attrelid = 'public.user_profiles'::regclass
                            AND attname = 'role_id')]::smallint[]
  ) THEN
    ALTER TABLE public.user_profiles
      ADD CONSTRAINT user_profiles_role_id_fkey
      FOREIGN KEY (role_id) REFERENCES public.roles(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'public.user_profiles'::regclass
      AND conname = 'user_profiles_identity_consistent'
  ) THEN
    ALTER TABLE public.user_profiles
      ADD CONSTRAINT user_profiles_identity_consistent
      CHECK (user_id = id);
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.sync_user_profile_role()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_role public.roles%ROWTYPE;
BEGIN
  IF NEW.role_name IS NOT NULL
     AND (TG_OP = 'INSERT' OR NEW.role_name IS DISTINCT FROM OLD.role_name) THEN
    SELECT * INTO v_role
    FROM public.roles
    WHERE name = CASE lower(NEW.role_name)
      WHEN 'médico' THEN 'medico'
      WHEN 'recepção' THEN 'recepcao'
      WHEN 'enfermeiro' THEN 'enfermagem'
      ELSE lower(NEW.role_name)
    END
      AND lg_ativo = TRUE;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'Perfil de acesso inválido: %', NEW.role_name;
    END IF;

    NEW.role_id := v_role.id;
    NEW.role_name := v_role.name;
  ELSIF NEW.role_id IS NOT NULL
        AND (TG_OP = 'INSERT' OR NEW.role_id IS DISTINCT FROM OLD.role_id) THEN
    SELECT * INTO v_role
    FROM public.roles
    WHERE id = NEW.role_id AND lg_ativo = TRUE;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'Perfil de acesso inválido: %', NEW.role_id;
    END IF;

    NEW.role_name := v_role.name;
  END IF;

  NEW.user_id := NEW.id;
  NEW.updated_at := NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_sync_user_profile_role ON public.user_profiles;
CREATE TRIGGER trg_sync_user_profile_role
BEFORE INSERT OR UPDATE OF id, user_id, role_id, role_name
ON public.user_profiles
FOR EACH ROW EXECUTE FUNCTION public.sync_user_profile_role();

-- ---------------------------------------------------------------------------
-- Helpers não recursivos usados pelas policies da própria user_profiles
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.auth_profile_company_id()
RETURNS UUID
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
SET row_security = off
AS $$
  SELECT company_id
  FROM public.user_profiles
  WHERE id = auth.uid() AND lg_ativo = TRUE;
$$;

CREATE OR REPLACE FUNCTION public.auth_is_company_admin()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
SET row_security = off
AS $$
  SELECT COALESCE(EXISTS (
    SELECT 1
    FROM public.user_profiles up
    LEFT JOIN public.roles r ON r.id = up.role_id
    WHERE up.id = auth.uid()
      AND up.lg_ativo = TRUE
      AND COALESCE(r.name, lower(up.role_name)) IN ('admin', 'administrador')
  ), FALSE);
$$;

REVOKE ALL ON FUNCTION public.auth_profile_company_id() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.auth_is_company_admin() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.auth_profile_company_id() TO authenticated;
GRANT EXECUTE ON FUNCTION public.auth_is_company_admin() TO authenticated;

DO $$
DECLARE
  v_unknown_policies TEXT[];
BEGIN
  SELECT array_agg(format('%I.%I', tablename, policyname) ORDER BY tablename, policyname)
    INTO v_unknown_policies
  FROM pg_policies
  WHERE schemaname = 'public'
    AND tablename IN ('user_profiles', 'roles', 'role_permissions')
    AND policyname NOT IN (
      'user_profiles_select_authorized',
      'user_profiles_insert_company_admin',
      'user_profiles_update_company_admin',
      'roles_select_authenticated',
      'role_permissions_select_company',
      'role_permissions_insert_company_admin',
      'role_permissions_update_company_admin'
    );

  IF v_unknown_policies IS NOT NULL THEN
    RAISE EXCEPTION
      'AUTH_FOUNDATION_PREFLIGHT: policies legadas/desconhecidas exigem reconciliação manual: %',
      v_unknown_policies;
  END IF;
END;
$$;

ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.role_permissions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS user_profiles_select_authorized ON public.user_profiles;
CREATE POLICY user_profiles_select_authorized
ON public.user_profiles
FOR SELECT TO authenticated
USING (
  (id = auth.uid() AND lg_ativo = TRUE)
  OR (
    public.auth_is_company_admin()
    AND company_id = public.auth_profile_company_id()
  )
);

DROP POLICY IF EXISTS user_profiles_insert_company_admin ON public.user_profiles;
CREATE POLICY user_profiles_insert_company_admin
ON public.user_profiles
FOR INSERT TO authenticated
WITH CHECK (
  public.auth_is_company_admin()
  AND company_id = public.auth_profile_company_id()
);

DROP POLICY IF EXISTS user_profiles_update_company_admin ON public.user_profiles;
CREATE POLICY user_profiles_update_company_admin
ON public.user_profiles
FOR UPDATE TO authenticated
USING (
  public.auth_is_company_admin()
  AND company_id = public.auth_profile_company_id()
)
WITH CHECK (
  public.auth_is_company_admin()
  AND company_id = public.auth_profile_company_id()
);

DROP POLICY IF EXISTS roles_select_authenticated ON public.roles;
CREATE POLICY roles_select_authenticated
ON public.roles
FOR SELECT TO authenticated
USING (lg_ativo = TRUE);

DROP POLICY IF EXISTS role_permissions_select_company ON public.role_permissions;
CREATE POLICY role_permissions_select_company
ON public.role_permissions
FOR SELECT TO authenticated
USING (company_id = public.auth_profile_company_id());

DROP POLICY IF EXISTS role_permissions_insert_company_admin ON public.role_permissions;
CREATE POLICY role_permissions_insert_company_admin
ON public.role_permissions
FOR INSERT TO authenticated
WITH CHECK (
  public.auth_is_company_admin()
  AND company_id = public.auth_profile_company_id()
);

DROP POLICY IF EXISTS role_permissions_update_company_admin ON public.role_permissions;
CREATE POLICY role_permissions_update_company_admin
ON public.role_permissions
FOR UPDATE TO authenticated
USING (
  public.auth_is_company_admin()
  AND company_id = public.auth_profile_company_id()
)
WITH CHECK (
  public.auth_is_company_admin()
  AND company_id = public.auth_profile_company_id()
);

REVOKE ALL ON public.user_profiles FROM anon;
REVOKE ALL ON public.roles FROM anon;
REVOKE ALL ON public.role_permissions FROM anon;
GRANT SELECT, INSERT, UPDATE ON public.user_profiles TO authenticated;
GRANT SELECT ON public.roles TO authenticated;
GRANT SELECT, INSERT, UPDATE ON public.role_permissions TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.role_permissions_id_seq TO authenticated;

ALTER TABLE public.role_permissions
  ALTER COLUMN company_id SET DEFAULT public.auth_profile_company_id();

-- ---------------------------------------------------------------------------
-- Auditoria: retornar o id persistido e preservar RLS nas estatísticas
-- ---------------------------------------------------------------------------
DROP FUNCTION IF EXISTS public.log_data_access(TEXT, TEXT, TEXT, JSONB);
CREATE FUNCTION public.log_data_access(
  p_tabela TEXT,
  p_registro_id TEXT,
  p_acao TEXT,
  p_contexto JSONB DEFAULT '{}'::JSONB
)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_log_id BIGINT;
  v_company_id UUID;
  v_user_id UUID;
  v_user_name TEXT;
  v_role TEXT;
BEGIN
  v_user_id := auth.uid();

  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Não autenticado';
  END IF;

  SELECT company_id, full_name, role_name
    INTO v_company_id, v_user_name, v_role
    FROM public.user_profiles
   WHERE id = v_user_id AND lg_ativo = TRUE;

  IF NOT FOUND OR v_company_id IS NULL THEN
    RAISE EXCEPTION 'Perfil ativo e empresa são obrigatórios';
  END IF;

  INSERT INTO public.audit_logs (
    company_id,
    cd_usuario, cd_usuario_nome, role_name,
    acao, tabela, registro_id, operacao,
    dados_novos
  ) VALUES (
    v_company_id,
    v_user_id, v_user_name, v_role,
    p_acao, p_tabela, p_registro_id,
    p_tabela || ' ' || p_acao || ' via API',
    p_contexto
  )
  RETURNING id INTO v_log_id;

  RETURN v_log_id;
END;
$$;

REVOKE ALL ON FUNCTION public.log_data_access(TEXT, TEXT, TEXT, JSONB) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.log_data_access(TEXT, TEXT, TEXT, JSONB) TO authenticated;

DROP VIEW IF EXISTS public.audit_logs_stats;
CREATE VIEW public.audit_logs_stats
WITH (security_invoker = true)
AS
SELECT
  company_id,
  DATE_TRUNC('day', dt_evento) AS dia,
  acao,
  tabela,
  cd_usuario,
  cd_usuario_nome,
  COUNT(*) AS total
FROM public.audit_logs
GROUP BY company_id, DATE_TRUNC('day', dt_evento), acao, tabela, cd_usuario, cd_usuario_nome;

GRANT SELECT ON public.audit_logs TO authenticated;
GRANT SELECT ON public.audit_logs_stats TO authenticated;
