-- Tenant isolation for LIS, NPS, pre-registration and notifications.
-- Existing functional authorization is retained and narrowed to the tenant.
-- Deliberately does not FORCE RLS; owner semantics are validated separately.
BEGIN;

DO $$
DECLARE
  target_table text;
BEGIN
  IF to_regprocedure('public.request_company_id()') IS NULL THEN
    RAISE EXCEPTION 'Operational RLS requires public.request_company_id()';
  END IF;
  IF to_regprocedure('public.current_company_id()') IS NULL THEN
    RAISE EXCEPTION 'Operational RLS requires public.current_company_id()';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_prontomedic') THEN
    RAISE EXCEPTION 'Operational RLS requires role app_prontomedic';
  END IF;

  FOREACH target_table IN ARRAY ARRAY[
    'exames_lab_catalogo', 'exames_lab_valor_referencia',
    'exames_lab_pedido', 'exames_lab_pedido_itens',
    'exames_lab_resultado', 'exames_lab_alerta_critico',
    'nps_pesquisas', 'nps_respostas', 'pre_cadastro',
    'notification_templates', 'notifications',
    'notification_preferences', 'notification_logs'
  ] LOOP
    IF to_regclass('public.' || target_table) IS NULL THEN
      RAISE EXCEPTION 'Operational RLS requires public.%', target_table;
    END IF;
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', target_table);
  END LOOP;
END
$$;

GRANT SELECT, INSERT, UPDATE, DELETE ON
  public.exames_lab_catalogo,
  public.exames_lab_valor_referencia,
  public.exames_lab_pedido,
  public.exames_lab_pedido_itens,
  public.exames_lab_resultado,
  public.exames_lab_alerta_critico,
  public.nps_pesquisas,
  public.nps_respostas,
  public.pre_cadastro,
  public.notification_templates,
  public.notifications,
  public.notification_preferences,
  public.notification_logs
TO app_prontomedic;

GRANT USAGE, SELECT ON SEQUENCE
  public.exames_lab_catalogo_id_seq,
  public.exames_lab_valor_referencia_id_seq,
  public.exames_lab_pedido_id_seq,
  public.exames_lab_pedido_itens_id_seq,
  public.exames_lab_resultado_id_seq,
  public.exames_lab_alerta_critico_id_seq,
  public.nps_pesquisas_id_seq,
  public.nps_respostas_id_seq,
  public.notification_logs_id_seq
TO app_prontomedic;

-- Remove only the permissive PUBLIC policies generated by the legacy baseline.
-- Their exact names are deterministic; functional named policies are handled below.
DO $$
DECLARE
  permissive_policy record;
BEGIN
  FOR permissive_policy IN
    SELECT schemaname, tablename, policyname
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = ANY (ARRAY[
        'exames_lab_catalogo', 'exames_lab_valor_referencia',
        'exames_lab_pedido', 'exames_lab_pedido_itens',
        'exames_lab_resultado', 'exames_lab_alerta_critico',
        'nps_pesquisas', 'nps_respostas', 'pre_cadastro',
        'notification_templates', 'notifications',
        'notification_preferences', 'notification_logs'
      ])
      AND policyname = tablename || '_' || lower(cmd)
      AND 'public' = ANY (roles)
  LOOP
    EXECUTE format(
      'DROP POLICY %I ON %I.%I',
      permissive_policy.policyname,
      permissive_policy.schemaname,
      permissive_policy.tablename
    );
  END LOOP;
END
$$;

-- Remove only policies whose expressions or role lists must be narrowed.
DROP POLICY IF EXISTS "Authenticated can read lab catalog" ON public.exames_lab_catalogo;
DROP POLICY IF EXISTS "Lab can manage exam catalog" ON public.exames_lab_catalogo;
DROP POLICY IF EXISTS "Authenticated can read lab ref values" ON public.exames_lab_valor_referencia;
DROP POLICY IF EXISTS "Lab can manage ref values" ON public.exames_lab_valor_referencia;
DROP POLICY IF EXISTS "Authenticated can read lab orders" ON public.exames_lab_pedido;
DROP POLICY IF EXISTS "Lab can manage lab orders" ON public.exames_lab_pedido;
DROP POLICY IF EXISTS "Authenticated can read lab order items" ON public.exames_lab_pedido_itens;
DROP POLICY IF EXISTS "Lab can manage lab order items" ON public.exames_lab_pedido_itens;
DROP POLICY IF EXISTS "Authenticated can read lab results" ON public.exames_lab_resultado;
DROP POLICY IF EXISTS "Lab can manage lab results" ON public.exames_lab_resultado;
DROP POLICY IF EXISTS "Authenticated can read lab alerts" ON public.exames_lab_alerta_critico;
DROP POLICY IF EXISTS "Lab can manage lab alerts" ON public.exames_lab_alerta_critico;

DROP POLICY IF EXISTS "Authenticated can read nps_pesquisas" ON public.nps_pesquisas;
DROP POLICY IF EXISTS "Admins can manage nps_pesquisas" ON public.nps_pesquisas;
DROP POLICY IF EXISTS "Authenticated can read nps_respostas" ON public.nps_respostas;
DROP POLICY IF EXISTS "Anonymous can submit NPS" ON public.nps_respostas;

DROP POLICY IF EXISTS "pre_cadastro_staff_select" ON public.pre_cadastro;
DROP POLICY IF EXISTS "pre_cadastro_staff_update" ON public.pre_cadastro;
DROP POLICY IF EXISTS "pre_cadastro_admin_delete" ON public.pre_cadastro;
DROP POLICY IF EXISTS "Admins can manage pre_cadastro" ON public.pre_cadastro;
DROP POLICY IF EXISTS "pre_cadastro_anon_insert" ON public.pre_cadastro;

DROP POLICY IF EXISTS "notification_templates_read" ON public.notification_templates;
DROP POLICY IF EXISTS "notification_templates_admin_write" ON public.notification_templates;
DROP POLICY IF EXISTS "notifications_read" ON public.notifications;
DROP POLICY IF EXISTS "notification_preferences_self" ON public.notification_preferences;
DROP POLICY IF EXISTS "notification_logs_admin" ON public.notification_logs;

-- LIS direct tables.
CREATE POLICY app_prontomedic_lis_catalogo_tenant ON public.exames_lab_catalogo
  FOR ALL TO app_prontomedic
  USING (company_id = public.request_company_id())
  WITH CHECK (company_id = public.request_company_id());
CREATE POLICY "Authenticated can read lab catalog" ON public.exames_lab_catalogo
  FOR SELECT TO authenticated
  USING (company_id = public.current_company_id());
CREATE POLICY "Lab can manage exam catalog" ON public.exames_lab_catalogo
  FOR ALL TO authenticated
  USING (company_id = public.current_company_id() AND public.is_lab_user(auth.uid()))
  WITH CHECK (company_id = public.current_company_id() AND public.is_lab_user(auth.uid()));

CREATE POLICY app_prontomedic_lis_pedido_tenant ON public.exames_lab_pedido
  FOR ALL TO app_prontomedic
  USING (company_id = public.request_company_id())
  WITH CHECK (company_id = public.request_company_id());
CREATE POLICY "Authenticated can read lab orders" ON public.exames_lab_pedido
  FOR SELECT TO authenticated
  USING (company_id = public.current_company_id());
CREATE POLICY "Lab can manage lab orders" ON public.exames_lab_pedido
  FOR ALL TO authenticated
  USING (company_id = public.current_company_id() AND public.is_lab_user(auth.uid()))
  WITH CHECK (company_id = public.current_company_id() AND public.is_lab_user(auth.uid()));

-- LIS child tables derive company through the real foreign-key chain.
CREATE POLICY app_prontomedic_lis_valor_tenant ON public.exames_lab_valor_referencia
  FOR ALL TO app_prontomedic
  USING (EXISTS (
    SELECT 1 FROM public.exames_lab_catalogo c
    WHERE c.id = cd_exame AND c.company_id = public.request_company_id()
  ))
  WITH CHECK (EXISTS (
    SELECT 1 FROM public.exames_lab_catalogo c
    WHERE c.id = cd_exame AND c.company_id = public.request_company_id()
  ));
CREATE POLICY "Authenticated can read lab ref values" ON public.exames_lab_valor_referencia
  FOR SELECT TO authenticated
  USING (EXISTS (
    SELECT 1 FROM public.exames_lab_catalogo c
    WHERE c.id = cd_exame AND c.company_id = public.current_company_id()
  ));
CREATE POLICY "Lab can manage ref values" ON public.exames_lab_valor_referencia
  FOR ALL TO authenticated
  USING (public.is_lab_user(auth.uid()) AND EXISTS (
    SELECT 1 FROM public.exames_lab_catalogo c
    WHERE c.id = cd_exame AND c.company_id = public.current_company_id()
  ))
  WITH CHECK (public.is_lab_user(auth.uid()) AND EXISTS (
    SELECT 1 FROM public.exames_lab_catalogo c
    WHERE c.id = cd_exame AND c.company_id = public.current_company_id()
  ));

CREATE POLICY app_prontomedic_lis_itens_tenant ON public.exames_lab_pedido_itens
  FOR ALL TO app_prontomedic
  USING (EXISTS (
    SELECT 1 FROM public.exames_lab_pedido p
    WHERE p.id = cd_pedido AND p.company_id = public.request_company_id()
  ))
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.exames_lab_pedido p
      WHERE p.id = cd_pedido AND p.company_id = public.request_company_id()
    )
    AND EXISTS (
      SELECT 1 FROM public.exames_lab_catalogo c
      WHERE c.id = cd_exame AND c.company_id = public.request_company_id()
    )
  );
CREATE POLICY "Authenticated can read lab order items" ON public.exames_lab_pedido_itens
  FOR SELECT TO authenticated
  USING (EXISTS (
    SELECT 1 FROM public.exames_lab_pedido p
    WHERE p.id = cd_pedido AND p.company_id = public.current_company_id()
  ));
CREATE POLICY "Lab can manage lab order items" ON public.exames_lab_pedido_itens
  FOR ALL TO authenticated
  USING (public.is_lab_user(auth.uid()) AND EXISTS (
    SELECT 1 FROM public.exames_lab_pedido p
    WHERE p.id = cd_pedido AND p.company_id = public.current_company_id()
  ))
  WITH CHECK (
    public.is_lab_user(auth.uid())
    AND EXISTS (
      SELECT 1 FROM public.exames_lab_pedido p
      WHERE p.id = cd_pedido AND p.company_id = public.current_company_id()
    )
    AND EXISTS (
      SELECT 1 FROM public.exames_lab_catalogo c
      WHERE c.id = cd_exame AND c.company_id = public.current_company_id()
    )
  );

CREATE POLICY app_prontomedic_lis_resultado_tenant ON public.exames_lab_resultado
  FOR ALL TO app_prontomedic
  USING (EXISTS (
    SELECT 1
    FROM public.exames_lab_pedido_itens i
    JOIN public.exames_lab_pedido p ON p.id = i.cd_pedido
    WHERE i.id = cd_item_pedido AND p.company_id = public.request_company_id()
  ))
  WITH CHECK (EXISTS (
    SELECT 1
    FROM public.exames_lab_pedido_itens i
    JOIN public.exames_lab_pedido p ON p.id = i.cd_pedido
    WHERE i.id = cd_item_pedido AND p.company_id = public.request_company_id()
  ));
CREATE POLICY "Authenticated can read lab results" ON public.exames_lab_resultado
  FOR SELECT TO authenticated
  USING (EXISTS (
    SELECT 1
    FROM public.exames_lab_pedido_itens i
    JOIN public.exames_lab_pedido p ON p.id = i.cd_pedido
    WHERE i.id = cd_item_pedido AND p.company_id = public.current_company_id()
  ));
CREATE POLICY "Lab can manage lab results" ON public.exames_lab_resultado
  FOR ALL TO authenticated
  USING (public.is_lab_user(auth.uid()) AND EXISTS (
    SELECT 1
    FROM public.exames_lab_pedido_itens i
    JOIN public.exames_lab_pedido p ON p.id = i.cd_pedido
    WHERE i.id = cd_item_pedido AND p.company_id = public.current_company_id()
  ))
  WITH CHECK (public.is_lab_user(auth.uid()) AND EXISTS (
    SELECT 1
    FROM public.exames_lab_pedido_itens i
    JOIN public.exames_lab_pedido p ON p.id = i.cd_pedido
    WHERE i.id = cd_item_pedido AND p.company_id = public.current_company_id()
  ));

CREATE POLICY app_prontomedic_lis_alerta_tenant ON public.exames_lab_alerta_critico
  FOR ALL TO app_prontomedic
  USING (EXISTS (
    SELECT 1
    FROM public.exames_lab_resultado r
    JOIN public.exames_lab_pedido_itens i ON i.id = r.cd_item_pedido
    JOIN public.exames_lab_pedido p ON p.id = i.cd_pedido
    WHERE r.id = cd_resultado AND p.company_id = public.request_company_id()
  ))
  WITH CHECK (EXISTS (
    SELECT 1
    FROM public.exames_lab_resultado r
    JOIN public.exames_lab_pedido_itens i ON i.id = r.cd_item_pedido
    JOIN public.exames_lab_pedido p ON p.id = i.cd_pedido
    WHERE r.id = cd_resultado AND p.company_id = public.request_company_id()
  ));
CREATE POLICY "Authenticated can read lab alerts" ON public.exames_lab_alerta_critico
  FOR SELECT TO authenticated
  USING (EXISTS (
    SELECT 1
    FROM public.exames_lab_resultado r
    JOIN public.exames_lab_pedido_itens i ON i.id = r.cd_item_pedido
    JOIN public.exames_lab_pedido p ON p.id = i.cd_pedido
    WHERE r.id = cd_resultado AND p.company_id = public.current_company_id()
  ));
CREATE POLICY "Lab can manage lab alerts" ON public.exames_lab_alerta_critico
  FOR ALL TO authenticated
  USING (public.is_lab_user(auth.uid()) AND EXISTS (
    SELECT 1
    FROM public.exames_lab_resultado r
    JOIN public.exames_lab_pedido_itens i ON i.id = r.cd_item_pedido
    JOIN public.exames_lab_pedido p ON p.id = i.cd_pedido
    WHERE r.id = cd_resultado AND p.company_id = public.current_company_id()
  ))
  WITH CHECK (public.is_lab_user(auth.uid()) AND EXISTS (
    SELECT 1
    FROM public.exames_lab_resultado r
    JOIN public.exames_lab_pedido_itens i ON i.id = r.cd_item_pedido
    JOIN public.exames_lab_pedido p ON p.id = i.cd_pedido
    WHERE r.id = cd_resultado AND p.company_id = public.current_company_id()
  ));

-- NPS: keep anonymous submission, but do not let that policy grant authenticated bypass.
CREATE POLICY "Anonymous can submit NPS" ON public.nps_respostas
  FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY app_prontomedic_nps_pesquisas_tenant ON public.nps_pesquisas
  FOR ALL TO app_prontomedic
  USING (company_id = public.request_company_id())
  WITH CHECK (company_id = public.request_company_id());
CREATE POLICY app_prontomedic_nps_respostas_tenant ON public.nps_respostas
  FOR ALL TO app_prontomedic
  USING (EXISTS (
    SELECT 1 FROM public.nps_pesquisas p
    WHERE p.id = cd_pesquisa AND p.company_id = public.request_company_id()
  ))
  WITH CHECK (EXISTS (
    SELECT 1 FROM public.nps_pesquisas p
    WHERE p.id = cd_pesquisa AND p.company_id = public.request_company_id()
  ));
CREATE POLICY "Authenticated can read nps_pesquisas" ON public.nps_pesquisas
  FOR SELECT TO authenticated USING (company_id = public.current_company_id());
CREATE POLICY "Admins can manage nps_pesquisas" ON public.nps_pesquisas
  FOR ALL TO authenticated
  USING (
    company_id = public.current_company_id()
    AND EXISTS (SELECT 1 FROM public.user_profiles WHERE id = auth.uid() AND role_name IN ('admin', 'gestor', 'administrador'))
  )
  WITH CHECK (
    company_id = public.current_company_id()
    AND EXISTS (SELECT 1 FROM public.user_profiles WHERE id = auth.uid() AND role_name IN ('admin', 'gestor', 'administrador'))
  );
CREATE POLICY "Authenticated can read nps_respostas" ON public.nps_respostas
  FOR SELECT TO authenticated USING (EXISTS (
    SELECT 1 FROM public.nps_pesquisas p
    WHERE p.id = cd_pesquisa AND p.company_id = public.current_company_id()
  ));

-- Pre-registration keeps public sign-up and tenant-scoped staff operations.
CREATE POLICY "pre_cadastro_anon_insert" ON public.pre_cadastro
  FOR INSERT TO anon
  WITH CHECK (
    length(full_name) >= 3
    AND length(cpf) IN (11, 14)
    AND length(email) >= 5
    AND email LIKE '%@%'
  );
CREATE POLICY app_prontomedic_pre_cadastro_tenant ON public.pre_cadastro
  FOR ALL TO app_prontomedic
  USING (company_id = public.request_company_id())
  WITH CHECK (company_id = public.request_company_id());
CREATE POLICY "pre_cadastro_staff_select" ON public.pre_cadastro
  FOR SELECT TO authenticated USING (company_id = public.current_company_id());
CREATE POLICY "pre_cadastro_staff_update" ON public.pre_cadastro
  FOR UPDATE TO authenticated
  USING (company_id = public.current_company_id())
  WITH CHECK (company_id = public.current_company_id());
CREATE POLICY "pre_cadastro_admin_delete" ON public.pre_cadastro
  FOR DELETE TO authenticated
  USING (
    company_id = public.current_company_id()
    AND EXISTS (SELECT 1 FROM public.user_profiles WHERE id = auth.uid() AND role_name = 'admin')
  );

-- Notification templates may be global, but global rows are read-only.
CREATE POLICY app_prontomedic_notification_templates_tenant ON public.notification_templates
  FOR ALL TO app_prontomedic
  USING (company_id = public.request_company_id())
  WITH CHECK (company_id = public.request_company_id());
CREATE POLICY "notification_templates_read" ON public.notification_templates
  FOR SELECT TO authenticated
  USING (company_id IS NULL OR company_id = public.current_company_id());
CREATE POLICY "notification_templates_admin_write" ON public.notification_templates
  FOR ALL TO authenticated
  USING (
    company_id = public.current_company_id()
    AND EXISTS (SELECT 1 FROM public.user_profiles WHERE id = auth.uid() AND role_name IN ('admin', 'manager'))
  )
  WITH CHECK (
    company_id = public.current_company_id()
    AND EXISTS (SELECT 1 FROM public.user_profiles WHERE id = auth.uid() AND role_name IN ('admin', 'manager'))
  );

CREATE POLICY app_prontomedic_notifications_tenant ON public.notifications
  FOR ALL TO app_prontomedic
  USING (company_id = public.request_company_id())
  WITH CHECK (company_id = public.request_company_id());
CREATE POLICY "notifications_read" ON public.notifications
  FOR SELECT TO authenticated
  USING (
    company_id = public.current_company_id()
    AND (
      recipient_id::text = auth.uid()::text
      OR EXISTS (SELECT 1 FROM public.user_profiles WHERE id = auth.uid() AND role_name IN ('admin', 'reception', 'manager'))
    )
  );

CREATE POLICY app_prontomedic_notification_preferences_tenant ON public.notification_preferences
  FOR ALL TO app_prontomedic
  USING (company_id = public.request_company_id())
  WITH CHECK (company_id = public.request_company_id());
CREATE POLICY "notification_preferences_self" ON public.notification_preferences
  FOR ALL TO authenticated
  USING (
    company_id = public.current_company_id()
    AND (
      recipient_id::text = auth.uid()::text
      OR EXISTS (SELECT 1 FROM public.user_profiles WHERE id = auth.uid() AND role_name IN ('admin', 'reception'))
    )
  )
  WITH CHECK (
    company_id = public.current_company_id()
    AND (
      recipient_id::text = auth.uid()::text
      OR EXISTS (SELECT 1 FROM public.user_profiles WHERE id = auth.uid() AND role_name IN ('admin', 'reception'))
    )
  );

CREATE POLICY app_prontomedic_notification_logs_tenant ON public.notification_logs
  FOR ALL TO app_prontomedic
  USING (EXISTS (
    SELECT 1 FROM public.notifications n
    WHERE n.id = notification_id AND n.company_id = public.request_company_id()
  ))
  WITH CHECK (EXISTS (
    SELECT 1 FROM public.notifications n
    WHERE n.id = notification_id AND n.company_id = public.request_company_id()
  ));
CREATE POLICY "notification_logs_admin" ON public.notification_logs
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.notifications n
      WHERE n.id = notification_id AND n.company_id = public.current_company_id()
    )
    AND EXISTS (SELECT 1 FROM public.user_profiles WHERE id = auth.uid() AND role_name IN ('admin', 'manager'))
  );

COMMIT;
