BEGIN;

CREATE TABLE IF NOT EXISTS public.nursing_medication_administrations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id UUID NOT NULL DEFAULT public.active_company_id() REFERENCES public.companies(id),
  unit_id BIGINT NOT NULL REFERENCES public.units(id),
  patient_id BIGINT NOT NULL REFERENCES public.patients(id),
  medication TEXT NOT NULL,
  dose TEXT,
  via TEXT,
  scheduled_at TIMESTAMPTZ,
  administered_at TIMESTAMPTZ,
  status TEXT NOT NULL DEFAULT 'pendente'
    CHECK (status IN ('pendente','em_preparo','administrado','recusado','suspenso','atrasado','cancelado')),
  bedside_check_ok BOOLEAN NOT NULL DEFAULT FALSE,
  refusal_reason TEXT,
  prepared_by BIGINT REFERENCES public.professionals(id),
  administered_by BIGINT REFERENCES public.professionals(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.nursing_incidents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id UUID NOT NULL DEFAULT public.active_company_id() REFERENCES public.companies(id),
  unit_id BIGINT NOT NULL REFERENCES public.units(id),
  patient_id BIGINT NOT NULL REFERENCES public.patients(id),
  incident_type TEXT NOT NULL,
  severity TEXT NOT NULL CHECK (severity IN ('leve','moderada','grave','critica')),
  description TEXT NOT NULL,
  medico_notificado BOOLEAN NOT NULL DEFAULT FALSE,
  reported_by BIGINT REFERENCES public.professionals(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.nursing_procedures (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id UUID NOT NULL DEFAULT public.active_company_id() REFERENCES public.companies(id),
  unit_id BIGINT NOT NULL REFERENCES public.units(id),
  patient_id BIGINT NOT NULL REFERENCES public.patients(id),
  procedure_type TEXT NOT NULL,
  description TEXT,
  performed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  performed_by BIGINT REFERENCES public.professionals(id),
  faturavel BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.nursing_shift_handoffs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id UUID NOT NULL DEFAULT public.active_company_id() REFERENCES public.companies(id),
  unit_id BIGINT NOT NULL REFERENCES public.units(id),
  patient_id BIGINT REFERENCES public.patients(id),
  notes TEXT,
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS nursing_medication_scope_idx
  ON public.nursing_medication_administrations(company_id, unit_id, status, scheduled_at);
CREATE INDEX IF NOT EXISTS nursing_incidents_scope_idx
  ON public.nursing_incidents(company_id, unit_id, created_at DESC);
CREATE INDEX IF NOT EXISTS nursing_procedures_scope_idx
  ON public.nursing_procedures(company_id, unit_id, performed_at DESC);
CREATE INDEX IF NOT EXISTS nursing_handoffs_scope_idx
  ON public.nursing_shift_handoffs(company_id, unit_id, created_at DESC);

ALTER TABLE public.nursing_medication_administrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.nursing_incidents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.nursing_procedures ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.nursing_shift_handoffs ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE
  table_name TEXT;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'nursing_medication_administrations',
    'nursing_incidents',
    'nursing_procedures',
    'nursing_shift_handoffs'
  ] LOOP
    EXECUTE format('DROP POLICY IF EXISTS nursing_care_select ON public.%I', table_name);
    EXECUTE format(
      'CREATE POLICY nursing_care_select ON public.%I FOR SELECT TO authenticated, app_prontomedic USING (
        company_id = public.active_company_id()
        AND (public.active_unit_id() IS NULL OR unit_id = public.active_unit_id())
        AND public.can_access(''prontuario'', ''view'')
      )',
      table_name
    );
    EXECUTE format('DROP POLICY IF EXISTS nursing_care_write ON public.%I', table_name);
    EXECUTE format(
      'CREATE POLICY nursing_care_write ON public.%I FOR ALL TO authenticated, app_prontomedic USING (
        company_id = public.active_company_id()
        AND (public.active_unit_id() IS NULL OR unit_id = public.active_unit_id())
        AND public.can_access(''prontuario'', ''edit'')
      ) WITH CHECK (
        company_id = public.active_company_id()
        AND (public.active_unit_id() IS NULL OR unit_id = public.active_unit_id())
        AND public.can_access(''prontuario'', ''edit'')
      )',
      table_name
    );
  END LOOP;
END $$;

GRANT SELECT, INSERT, UPDATE ON
  public.nursing_medication_administrations,
  public.nursing_incidents,
  public.nursing_procedures,
  public.nursing_shift_handoffs
TO authenticated, app_prontomedic;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated, app_prontomedic;

COMMIT;
